# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170824_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitian',
            name='dosen',
            field=models.ManyToManyField(to='base.Dosen'),
        ),
        migrations.AddField(
            model_name='penelitian',
            name='mahasiswa',
            field=models.ManyToManyField(to='base.Mahasiswa'),
        ),
    ]
