# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170824_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'ordering': ['nim']},
        ),
    ]
