# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170824_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='dosen',
            field=models.ManyToManyField(blank=True, to='base.Dosen'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='mahasiswa',
            field=models.ManyToManyField(blank=True, to='base.Mahasiswa'),
        ),
    ]
