# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170828_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='fakultas',
            field=models.CharField(default='fakultasxx', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='program_studi',
            field=models.CharField(default='prodixx', max_length=30),
            preserve_default=False,
        ),
    ]
