# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170829_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='fakultas',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='program_studi',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='fakultas_dan_program_studi',
            field=models.CharField(choices=[('Ekonomi', (('ak', 'Akuntansi'), ('man', 'Manajemen'))), ('hu', 'Hukum'), ('ik', 'Ilmu Komputer'), ('so', 'Ilmu Sosial dan Politik'), ('pe', 'Pertanian'), ('te', 'Teknik')], default='ak', max_length=30),
            preserve_default=False,
        ),
    ]
