# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170829_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='program_studi',
            field=models.CharField(choices=[('Fakultas Ekonomi', (('ak', 'Akuntansi'), ('man', 'Manajemen'))), ('Fakultas Teknik', (('ar', 'Arsitektur'), ('el', 'Elektro')))], max_length=30),
        ),
    ]
