# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20170829_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='judul',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
