# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20170901_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='gelar_belakang',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosen',
            name='gelar_depan',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
