# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170904_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='program_studi',
            field=models.CharField(choices=[(b'Fakultas Ekonomi', ((b'ak', b'Akuntansi'), (b'man', b'Manajemen'))), (b'Fakultas Ilmu Komputer', ((b'si', b'Sistem Informasi'), (b'ti', b'Teknik Informatika'))), (b'Fakultas Hukum', ((b'pe', b'Perdata'), (b'pi', b'Pidana'), (b'za', b'TEST hukum'))), (b'Fakultas Teknik', ((b'ar', b'Arsitektur'), (b'el', b'Elektro'))), (b'Fakultas Ilmu Sosial, Ilmu Politik', ((b'ko', b'Komunikasi'), (b'ad', b'Administrasi'))), (b'Fakultas Pertanian', ((b'ab', b'Agribisnis'), (b'thp', b'Teknologi Hasil Pertanian')))], max_length=30),
        ),
    ]
