# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20170904_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='program_studi',
            field=models.CharField(choices=[('Fakultas Ekonomi', (('ak', 'Akuntansi'), ('man', 'Manajemen'))), ('Fakultas Ilmu Komputer', (('ti', 'Teknik Informatika'), ('ti', '-'))), ('Fakultas Hukum', (('hu', 'Ilmu Hukum'), ('hu', '-'))), ('Fakultas Teknik', (('ar', 'Arsitektur'), ('el', 'Elektro'))), ('Fakultas Ilmu Sosial, Ilmu Politik', (('ko', 'Komunikasi'), ('ip', 'Ilmu Pemerintahan'))), ('Fakultas Pertanian', (('agb', 'Agribisnis'), ('agr', 'Agroteknologi'), ('thp', 'Teknologi Hasil Pertanian')))], max_length=30),
        ),
    ]
