# Generated by Django 2.1.5 on 2019-01-18 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20170905_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='nama',
            new_name='nama_lengkap',
        ),
    ]
