# Generated by Django 2.1.5 on 2019-01-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20190118_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitian',
            name='berkas_publikasi',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
