# Generated by Django 2.1.5 on 2019-01-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_dosen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nidn',
            field=models.CharField(default='0123', max_length=20),
        ),
    ]
