# Generated by Django 2.1.5 on 2019-01-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20190123_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nidn',
            field=models.CharField(default='0123', max_length=20, unique=True),
        ),
    ]
