# Generated by Django 2.1.5 on 2019-01-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20190123_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='program_studi',
            field=models.CharField(blank=True, choices=[('Fakultas Ekonomi', (('ak', 'Akuntansi'), ('man', 'Manajemen'))), ('Fakultas Ilmu Komputer', (('ti', 'Teknik Informatika'), ('ti', '-'))), ('Fakultas Hukum', (('hu', 'Ilmu Hukum'), ('hu', '-'))), ('Fakultas Teknik', (('ar', 'Arsitektur'), ('el', 'Elektro'))), ('Fakultas Ilmu Sosial, Ilmu Politik', (('ko', 'Komunikasi'), ('ip', 'Ilmu Pemerintahan'))), ('Fakultas Pertanian', (('agb', 'Agribisnis'), ('agr', 'Agroteknologi'), ('thp', 'Teknologi Hasil Pertanian')))], max_length=30, null=True),
        ),
    ]
