# Generated by Django 2.1.5 on 2019-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_dosen_program_studi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='gelar_depan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
