# Generated by Django 2.1.5 on 2019-01-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20190123_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='berkas_publikasi',
            field=models.FileField(blank=True, null=True, upload_to='publikasi'),
        ),
    ]
