# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratIzinPenelitianMahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Mahasiswa')),
                ('penelitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Penelitian')),
            ],
        ),
    ]
