# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('lemlit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetugasAdmininistrasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrukturManajemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=30)),
                ('nama_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dosen')),
            ],
        ),
    ]
