# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0002_petugasadmininistrasi_strukturmanajemen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratizinpenelitianmahasiswa',
            name='mahasiswa',
        ),
    ]
