# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0005_suratizinpenelitianmahasiswa_disetujui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratizinpenelitianmahasiswa',
            name='penelitian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Penelitian', unique=True),
        ),
    ]
