# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0006_auto_20170825_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratizinpenelitianmahasiswa',
            name='penelitian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Penelitian'),
        ),
    ]
