# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170824_0405'),
        ('lemlit', '0007_auto_20170825_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratizinpenelitianmahasiswa',
            name='penelitian',
        ),
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='penelitian',
            field=models.ManyToManyField(to='base.Penelitian'),
        ),
    ]
