# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0008_auto_20170828_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='distempel',
            field=models.BooleanField(default=False),
        ),
    ]
