# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170828_1247'),
        ('lemlit', '0009_suratizinpenelitianmahasiswa_distempel'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='mahasiswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Mahasiswa'),
        ),
        migrations.RemoveField(
            model_name='suratizinpenelitianmahasiswa',
            name='penelitian',
        ),
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='penelitian',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.Penelitian'),
            preserve_default=False,
        ),
    ]
