# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0011_suratizinpenelitianmahasiswa_dosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratizinpenelitianmahasiswa',
            name='dosen',
        ),
    ]
