# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0012_remove_suratizinpenelitianmahasiswa_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='nama_instansi',
            field=models.CharField(default='Nama Kantor', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='nomor_surat',
            field=models.CharField(default='xxx/LEMLIT-UNISAN/GTO/VIII/2017', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='tujuan_surat',
            field=models.CharField(default='Gorontalo', max_length=20),
            preserve_default=False,
        ),
    ]
