# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0013_auto_20170901_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suratizinpenelitianmahasiswa',
            options={'ordering': ['created', 'updated']},
        ),
    ]
