# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0014_auto_20170904_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratKeteranganPenelitianMahasiswa',
            fields=[
                ('suratizinpenelitianmahasiswa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lemlit.SuratIzinPenelitianMahasiswa')),
            ],
            bases=('lemlit.suratizinpenelitianmahasiswa',),
        ),
    ]
