# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0015_suratketeranganpenelitianmahasiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='petugas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suratizinpenelitianmahasiswa',
            name='nomor_surat',
            field=models.CharField(max_length=50),
        ),
    ]
