# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0016_auto_20170908_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratizinpenelitianmahasiswa',
            name='untuk_pembayaran',
            field=models.CharField(choices=[(b'Surat Keterangan', b'Surat Keterangan'), (b'Surat Izin Penelitian', b'Surat Izin Penelitian')], default=b'Surat Izin Penelitian', max_length=25),
        ),
    ]
