# Generated by Django 2.1.5 on 2019-01-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0017_suratizinpenelitianmahasiswa_untuk_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratizinpenelitianmahasiswa',
            name='untuk_pembayaran',
            field=models.CharField(choices=[('Surat Keterangan', 'Surat Keterangan'), ('Surat Izin Penelitian', 'Surat Izin Penelitian')], default='Surat Izin Penelitian', max_length=25),
        ),
    ]
