# Generated by Django 2.1.5 on 2019-01-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_penelitian_berkas_publikasi'),
        ('lemlit', '0018_auto_20190113_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='HibahPenelitian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('periode', models.CharField(choices=[('gasal', 'Gasal'), ('genap', 'Genap')], max_length=5)),
                ('berkas_proposal', models.FileField(upload_to='')),
                ('laporan_akhir', models.FileField(upload_to='')),
                ('penelitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hibah_penelitian_internal', to='base.Penelitian')),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('judul', models.CharField(max_length=30)),
                ('deskripsi', models.TextField()),
                ('berkas', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('progress', models.CharField(choices=[('pengajuan', 'Pengajuan'), ('review', 'Tahap Review'), ('diterima', 'Diterima'), ('selesai', 'Selesai')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='hibahpenelitian',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hibah_penelitian', to='lemlit.Status'),
        ),
    ]
