# Generated by Django 2.1.5 on 2019-01-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemlit', '0019_auto_20190123_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='hibahpenelitian',
            name='dosen',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='hibahpenelitian',
            name='program_studi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
